name: Asterisk
version: 2.4.0
slug: asterisk
description: PBX server for SIP devices like doorbells and phones
url: https://github.com/TECH7Fox/asterisk-hass-addons
image: "ghcr.io/tech7fox/{arch}-addon-asterisk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
map:
  - config:rw
  - ssl
options:
  video_support: true
  auto_add: true
  generate_ssl_cert: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  mailbox: false
  mailbox_port: 12345
  mailbox_extension: "100"
  log_level: notice
schema:
  ami_password: password
  video_support: bool
  auto_add: bool
  auto_add_secret: password?
  generate_ssl_cert: bool
  certfile: str
  keyfile: str
  mailbox: bool
  mailbox_port: port?
  mailbox_password: password?
  mailbox_extension: str?
  mailbox_google_api_key: password?
  log_level: list(all|trace|debug|info|notice|warning|error|fatal|off)
host_network: true
init: false
uart: true # chan-dongle requirement
